### ISSUE TITLE
the GPU program failed to execute at /tmp/pip-req-build-jh50bw28/aten/src/THC/THCBlas.cu:450

### ISSUE THREAD

**Issue by wh277** [kiharalab/Emap2secPlus#13]
Hello, I had install pytorch=1.1.0 and cudatoolkit=10.0, but  cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-jh50bw28/aten/src/THC/THCBlas.cu:450.

ubuntu20.04, GPU RTX 4060 laptop 8G

![微信图片_20230513152715](https://github.com/kiharalab/Emap2secPlus/assets/125532384/121c3712-b6b9-495d-af44-241f5d32c5dc)

**Comment by wang3702** [comment]
I think it did not match well with your cuda version with some reasons. Can you try 
```
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
```
Also, if you only run one or two maps, please also consider to run https://bit.ly/emap2secplus or https://doi.org/10.24433/CO.7165707.v1. They are free and no dependencies are needed.

**Comment by wh277** [comment]
thanks，I will try these
